## Assignment 
Apply Bayes' Theorem to solve a medical diagnosis problem given conditional probabilities.Find the eigenvalues and corresponding eigenvectors of a given matrix.Calculate the determinant of a 3x3 matrix and find its inverse if possible.Describe the properties and applications of the Normal distribution and calculate probabilities using its properties 

In [14]:
import numpy as np
import scipy.stats as stats


In [15]:
# 1. Apply Bayes' Theorem
def bayes_theorem(prior_A, prob_B_given_A, prob_B):
    """
    Apply Bayes' Theorem.
    P(A|B) = (P(B|A) * P(A)) / P(B)
    """
    posterior_A_given_B = (prob_B_given_A * prior_A) / prob_B
    return posterior_A_given_B

In [16]:
# 2. Eigenvalues and Eigenvectors
def eigen_decomposition(matrix):
    eigenvalues, eigenvectors = np.linalg.eig(matrix)
    return eigenvalues, eigenvectors


In [17]:
# 3. Determinant and Inverse of a 3x3 Matrix
def matrix_determinant(matrix):
    """
    Calculate the determinant of a 3x3 matrix.
    """
    det = np.linalg.det(matrix)
    return det

In [18]:
def matrix_inverse(matrix):
    """
    Calculate the inverse of a 3x3 matrix if possible.
    """
    det = matrix_determinant(matrix)
    if det == 0:
        return None  # The matrix is singular and cannot be inverted.
    inverse = np.linalg.inv(matrix)
    return inverse

In [19]:
# 4. Normal Distribution
def normal_distribution_properties():
    """
    Describe properties of the Normal distribution.
    """
    properties = {
        "Mean (μ)": "The center of the distribution.",
        "Standard Deviation (σ)": "Measures the spread of the distribution.",
        "Symmetry": "The normal distribution is symmetric about the mean.",
        "68-95-99.7 Rule": "Approximately 68% of the data falls within 1σ, 95% within 2σ, and 99.7% within 3σ."
    }
    return properties

In [20]:
def normal_distribution_probability(mean, std_dev, value):
    """
    Calculate the probability of a value in a normal distribution.
    """
    probability = stats.norm.cdf(value, loc=mean, scale=std_dev)
    return probability

In [21]:
# Bayes' Theorem
prior_A = 0.01  # Prior probability of having the disease
prob_B_given_A = 0.9  # Probability of a positive test given the disease
prob_B = 0.05  # Probability of a positive test
posterior = bayes_theorem(prior_A, prob_B_given_A, prob_B)
print(f"Posterior Probability: {posterior:.4f}")
    

Posterior Probability: 0.1800


In [22]:
# Eigenvalues and Eigenvectors
matrix = np.array([[4, 2, 0], [2, 4, 2], [0, 2, 4]])
eigenvalues, eigenvectors = eigen_decomposition(matrix)
print(f"Eigenvalues: {eigenvalues}")
print(f"Eigenvectors: {eigenvectors}")

Eigenvalues: [6.82842712 4.         1.17157288]
Eigenvectors: [[-5.00000000e-01  7.07106781e-01  5.00000000e-01]
 [-7.07106781e-01  4.05405432e-16 -7.07106781e-01]
 [-5.00000000e-01 -7.07106781e-01  5.00000000e-01]]


In [23]:
# Determinant and Inverse of a 3x3 Matrix
det = matrix_determinant(matrix)
inverse = matrix_inverse(matrix)
print(f"Determinant: {det:.4f}")
if inverse is not None:
    print(f"Inverse: \n{inverse}")
else:
    print("The matrix is singular and cannot be inverted.")

Determinant: 32.0000
Inverse: 
[[ 0.375 -0.25   0.125]
 [-0.25   0.5   -0.25 ]
 [ 0.125 -0.25   0.375]]


In [24]:
# Normal Distribution Properties and Probabilities
properties = normal_distribution_properties()
print("Normal Distribution Properties:")
for key, value in properties.items():
    print(f"{key}: {value}")

Normal Distribution Properties:
Mean (μ): The center of the distribution.
Standard Deviation (σ): Measures the spread of the distribution.
Symmetry: The normal distribution is symmetric about the mean.
68-95-99.7 Rule: Approximately 68% of the data falls within 1σ, 95% within 2σ, and 99.7% within 3σ.


In [25]:
mean = 0
std_dev = 1
value = 1.96
probability = normal_distribution_probability(mean, std_dev, value)
print(f"Probability of {value} in N({mean}, {std_dev}^2): {probability:.4f}")

Probability of 1.96 in N(0, 1^2): 0.9750
